
resource "cloudflare_record" "terraform-test" {
  # required
  zone_id = cloudflare_zone.terraform-cloudfeeling-com.id
  name    = "@"
  type    = "CNAME"
  # optional
  value   = "oracle.cloudfeeling.com"
  proxied = true
  comment = "Generated by Terraform"
  tags = ["terraform", "cname"]
  #allow_overwrite = True
}
